name: "Eggplant Runner"

# Configure which branch that will trigger Eggplant DAI GitHub Action
on: 

  push:
   branches: [ "main" ]
  #pull_request:
   # branches:[ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.4
        with:
          serverURL: "http://vm1c02x1e4ejg5j" # Required. Details below
          testConfigID: "631e49ed-bb03-45eb-8c9f-c10b69725660" # Required. Details below
          clientSecret: "3a540fce-8d46-4d29-848e-436660a25569" # Required. Details below
