name: "Eggplant Runner"

# Configure which branch that will trigger Eggplant DAI GitHub Action
on: "darrahhoughgittest"
#  push:
#    branches:
#      - main 
#  pull_request:
#    branches:
#      - main

jobs:
  Run-DAI-Test-Configuration:
    strategy: # Optional configuration by using matrix strategy
      max-parallel: 1 # To set the maximum number of jobs that can run simultaneously 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Operating support by Eggplant DAI GitHub Action
    runs-on: ${{ windows-latest.os }} # Provide OS matrix
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@1.0.0
        with:
          serverURL: "http://vm1c02x1e4ejg5j:8000/" # Required. Details below
          testConfigID: "631e49ed-bb03-45eb-8c9f-c10b69725660" # Required. Details below
          clientSecret: "3a540fce-8d46-4d29-848e-436660a25569" # Required. Details below
