name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@main
        with:
          dryRun: true
          serverURL: "http://vm1c02x1e4ejg5j:8000"
          testConfigID: "e56fe0e9-c65c-442c-864d-5b4a67b98eab"# Test configuration which need to perform execution
          clientSecret: "3a540fce-8d46-4d29-848e-436660a25569"# Eggplant DAI service client secret
          # Alternatively, DAI client secret can be set as repo secret
          # by going to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
         
          
exit  
